# -*- coding: utf-8 -*-
# see org.apache.directory.fortress.core.GlobalIds.java
import datetime

AUTHZ_COMPARE_FAILURE_FLAG = 5

FAILED_AUTHZ_INDICATOR = "%failed%"

FT_PREFIX = "ft"

FT_MODIFIER_AUX_OBJECT_CLASS_NAME = "ftMods"

FT_MODIFIER = "ftModifier"

FT_MODIFIER_CODE = "ftModCode"

FT_MODIFIER_ID = "ftModId"

FT_IID = "ftId"

FILTER_PREFIX = "(&(%s="

FILTER_TRUE = "(objectClass=*)"

PROPS_AUX_OBJECT_CLASS_NAME = "ftProperties"

PROPS = "ftProps"

ROLE_OBJECT_CLASS_NM = "ftRls"

CONSTRAINT = "ftCstr"

USER_ROLE_ASSIGN = "ftRA"

USER_ROLE_DATA = "ftRC"

USER_ADMINROLE_ASSIGN = "ftARA"

USER_ADMINROLE_DATA = "ftARC"

POBJ_NAME = "ftObjNm"

POBJ_ID = "ftObjId"

PARENT_NODES = "ftParents"

TYPE = "ftType"

USERID_LEN = 40

ROLE_LEN = 40

DESC_LEN = 180

PERM_LEN = 100

PASSWORD_LEN = 50

PWPOLICY_NAME_LEN = 40

OU_LEN = 40

SN_LEN = 80

CN_LEN = 80

PROP_LEN = 100

REG_EX_SAFE_TEXT = "regXSafetext"

LDAP_FILTER = "ldap.filter."

LDAP_SUB = "ldap.sub."

LDAP_FILTER_SIZE_PROP = "ldap.filter.size"

AUTH_Z_FAILED = "authzfailed"

POP_NAME = "ftOpNm"

AUTH_Z_FAILED_VALUE = POP_NAME + "=" + AUTH_Z_FAILED

UID_NUMBER = "uidNumber"
GID_NUMBER = "gidNumber"
HOME_DIRECTORY = "homeDirectory"
LOGIN_SHELL = "loginShell"
GECOS = "gecos"
SYSTEM_USER = "ftSystem"

OPENLDAP_POLICY_SUBENTRY = "pwdPolicySubentry"
OPENLDAP_PW_RESET = "pwdReset"
OPENLDAP_PW_LOCKED_TIME = "pwdAccountLockedTime"
OPENLDAP_ACCOUNT_LOCKED_TIME = "pwdAccountLockedTime"
LOCK_VALUE = "000001010000Z"

JWT_SECRET = 'secret'
JWT_ALGORITHM = 'HS256'
JWT_EXPIRED_TIMEDELTA = datetime.timedelta(hours=8)
JWT_LEEWAY = datetime.timedelta(minutes=10)

ROLE_NAME_ADMIN = 'Admin'
ROLE_NAME_MANAGER = 'Manager'
ROLE_NAME_LOGIN_USER = 'LoginUser'

PERMISSION_BASE_MASK = 0b00000000
PERMISSION_READ_MASK = 0b10000000
PERMISSION_WRITE_MASK = 0b01000000
PERMISSION_EXECUTE_MASK = 0b00100000
PERMISSION_DELETE_MASK = 0b00010000
PERMISSION_LIST_MASK = 0b00001000
PERMISSION_INFO_MASK = 0b00000100
PERMISSION_READ_ONLY = 0b10001100
PERMISSION_READ_WRITE = 0b11001100
PERMISSION_CRUD = 0b11011100
PERMISSION_FULL_CONTROL = 0b11111111

SECURITY_IDENTITY_USER_PREFIX = 'usr:'
SECURITY_IDENTITY_ROLE_PREFIX = 'role:'
SECURITY_IDENTITY_GROUP_PREFIX = 'grp:'
